services:  
  db:
    image: postgres:latest
    ports: 
      - '5433:5432'
    environment:
      - POSTGRES_DB=TEST
      - POSTGRES_PASSWORD=supersecret
      - POSTGRES_USER=nofoobar
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - ./hrms_db_data:/var/lib/postgresql/data/pgdata
    restart: always

volumes:
  db_data: